@startuml monolith_context
!include <C4/C4_Context>

title Диаграмма контекста: Монолитная система управления Умным домом

Person(клиент, "Клиент", "Управляет температурой, подключает устройства")
Person(поддержка, "Поддержка", "Осуществляет подключение и отключение датчиков в систему")
System(умный_дом, "Умный дом", "Управляет датчиками и проверяет температуру")

System_Ext(датчик, "Датчик температуры", "Принимает команды")

Rel(клиент, поддержка, "Запрашивает подключение и отключение датчиков")
Rel(поддержка, датчик, "Подключает, отключает датчик")
Rel(клиент, умный_дом, "Управляет температурой через веб-интерфейс")
Rel(умный_дом, датчик, "Посылает команды на изменение температуры, считывает показатели")
@enduml